<?php

//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'combodo-background-task-extended/1.0.3',
	[
		// Identification
		//
		'label' => 'Background task extended',
		'category' => 'business',

		// Setup
		//
		'dependencies' => [
			'itop-structure/3.2.0',
		],
		'mandatory' => true,
		'visible' => true,

		// Components
		//
		'datamodel' => [
			'vendor/autoload.php',
			'src/Model/AbstractTimeRangeWeeklyScheduledProcess.php',
			'src/Model/AbstractBackgroundTaskExAction.php',
			'model.combodo-background-task-extended.php', // Contains the PHP code generated by the "compilation" of datamodel.combodo-background-task-extended.xml
		],
		'webservice' => [

		],
		'data.struct' => [
			// add your 'structure' definition XML files here,
		],
		'data.sample' => [
			// add your sample data XML files here,
		],

		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any

		// Default settings
		//
		'settings' => [
			// Module specific settings go here, if any
		],
	]
);
