<?php
/*
 * @copyright   Copyright (C) 2010-2022 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */


use Combodo\iTop\ComplexBackgroundTask\Service\TimeRangeWeeklyScheduledService;

abstract class AbstractTimeRangeWeeklyScheduledProcess extends AbstractWeeklyScheduledProcess
{
	const MODULE_SETTING_MAX_TIME = 'end_time';

	protected function GetDefaultModuleSettingTime(){
		return '01:00';
	}

	protected function GetDefaultModuleSettingEndTime(){
		return '05:00';
	}

	/**
	 * @throws \Combodo\iTop\ComplexBackgroundTask\Helper\ComplexBackgroundTaskException
	 * @throws \ProcessInvalidConfigException
	 * @throws \Exception
	 */
	public function GetNextOccurrence($sCurrentTime = 'now')
	{
		$oAnonymizerService = $this->GetWeeklyScheduledService();
		$iCurrentTime = (new DateTime($sCurrentTime))->getTimestamp();
		return $oAnonymizerService->GetNextOccurrence($iCurrentTime); // TODO: Change the autogenerated stub
	}

	/**
	 * @return \Combodo\iTop\ComplexBackgroundTask\Service\TimeRangeWeeklyScheduledService
	 * @throws \ProcessInvalidConfigException
	 */
	public function GetWeeklyScheduledService(): TimeRangeWeeklyScheduledService
	{
		$oAnonymizerService = new TimeRangeWeeklyScheduledService();
		$bEnabled = MetaModel::GetConfig()->GetModuleSetting($this->GetModuleName(), static::MODULE_SETTING_ENABLED, static::DEFAULT_MODULE_SETTING_ENABLED);
		$sStartTime = MetaModel::GetConfig()->GetModuleSetting($this->GetModuleName(), static::MODULE_SETTING_TIME, $this->GetDefaultModuleSettingTime());
		$sEndTime = MetaModel::GetModuleSetting($this->GetModuleName(), static::MODULE_SETTING_MAX_TIME, $this->GetDefaultModuleSettingEndTime());
		// TODO ????
		$sTimeLimit = time() + 100;

		$oAnonymizerService->SetEnabled($bEnabled);
		$oAnonymizerService->SetStartTime($sStartTime);
		$oAnonymizerService->SetEndTime($sEndTime);
		$oAnonymizerService->SetTimeLimit($sTimeLimit);
		$oAnonymizerService->SetDays($this->InterpretWeekDays());

		return $oAnonymizerService;
	}

}